### ISSUE TITLE
TypeError: argument should be integer or bytes-like object, not 'str'

### ISSUE THREAD

**Issue by Villelmo** [HadesNull123/xvideos#2]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2031, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2017, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2014, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1529, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1527, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1513, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lulu/xvideos/app.py", line 15, in check
    equals = download_xvideos(link)
  File "/home/lulu/xvideos/utils/downloadXvideos.py", line 21, in download_xvideos
    video_Low = get_link('html5player.setVideoUrlLow', text_raw)
  File "/home/lulu/xvideos/utils/downloadXvideos.py", line 10, in get_link
    if (line.find(title) != -1):
TypeError: argument should be integer or bytes-like object, not 'str'

**Comment by HadesNull123** [comment]
You can run it with python 2.
If necessary, I can help you with teamview. Please contact me from 9AM - 5PM. GMT +7.

**Comment by Villelmo** [comment]
Teamviewer?. It's a great idea. What's your username?.

**Comment by Villelmo** [comment]
Ready, now i can execute the script.

**Comment by HadesNull123** [comment]
Hi, 
I sorry.
I just came back from work
